// src/handlers/messageActions/types.ts

/**
 * Shared Types for Message Action Handlers
 *
 * Contains enums and interfaces used across all action handlers
 * and the message orchestrator service.
 *
 * IMPORTANT: Use enums instead of magic strings!
 */

import type { ChatMessage, NewEmailPayload } from '../../types';
import type { IAIChatService, AIChatSession, UserContent } from '../../services/aiService';
import type { AIActionResponse } from '../../services/aiSchema';
import type { TurnTokenUsage } from '../../services/conversationHistoryService';

// ============================================================================
// ENUMS (No magic strings!)
// ============================================================================

/**
 * Types of actions that can be triggered by AI responses
 */
export enum ActionType {
  CALENDAR = 'calendar',
  SELFIE = 'selfie',
  VIDEO = 'video',
  GIF = 'gif',
  EMAIL = 'email',
  NONE = 'none',
}

/**
 * Types of calendar queries detected in user messages
 */
export enum CalendarQueryType {
  /** No calendar-related query */
  NONE = 'none',
  /** Reading calendar (e.g., "What's on my calendar?") */
  READ = 'read',
  /** Modifying calendar (e.g., "Add meeting", "Delete event") */
  WRITE = 'write',
}

/**
 * Stages of message processing (for logging/debugging)
 */
export enum ProcessingStage {
  /** Initial setup and validation */
  PREPROCESSING = 'preprocessing',
  /** Calling the AI service */
  AI_CALL = 'ai_call',
  /** Routing to action handlers */
  ACTION_ROUTING = 'action_routing',
  /** Background processing (facts, presence) */
  POSTPROCESSING = 'postprocessing',
  /** Successfully completed */
  COMPLETE = 'complete',
  /** Failed with error */
  ERROR = 'error',
}

// ============================================================================
// ORCHESTRATOR INTERFACES
// ============================================================================

/**
 * Input to the message orchestrator
 */
export interface OrchestratorInput {
  /** The user's message text */
  userMessage: string;

  /** Optional user message text for AI (e.g., includes attachment contents). */
  userMessageForAI?: string;

  /** Optional rich user content (image + text, audio, etc.) */
  userContent?: UserContent;

  /** AI service instance to use */
  aiService: IAIChatService;

  /** Current AI session (may be null for first message) */
  session: AIChatSession | null;

  /** Current chat history for context */
  chatHistory: ChatMessage[];

  /** Whether audio is muted */
  isMuted: boolean;

  /**
   * The email Kayley is currently waiting on Steven to decide about.
   * When set, the orchestrator injects email context into the user message
   * so the AI can call the email_action FUNCTION TOOL when needed.
   */
  pendingEmail?: NewEmailPayload | null;

  /** Channel-scoped conversation id for payloads and deferred UI state. */
  conversationScopeId?: string;

  /** SSE event bus for streaming tool/action visibility to web clients. */
  eventBus?: { emit(event: string, data: unknown): boolean };
}

export interface PendingTweetDraft {
  id: string;
  tweetText: string;
  includeSelfie: boolean;
  selfieScene?: string | null;
}

/**
 * Result from the message orchestrator
 * Contains everything needed to update the UI
 */
export interface OrchestratorResult {
  // ---- Status ----
  /** Whether processing completed successfully */
  success: boolean;

  /** What type of action was processed */
  actionType: ActionType;

  /** Which stage completed (for debugging) */
  stage: ProcessingStage;

  // ---- Chat Updates ----
  /** Messages to add to chat history */
  chatMessages: ChatMessage[];

  // ---- Media ----
  /** Base64 audio to play (if any) */
  audioToPlay?: string;

  /** Action ID to play (if any) */
  actionToPlay?: string;

  // ---- Navigation ----
  /** URL to open (if any) */
  appToOpen?: string;

  // ---- State Refresh Flags ----
  /** Should refresh calendar events */
  refreshCalendar: boolean;

  // ---- Session ----
  /** Updated AI session (if changed) */
  updatedSession?: AIChatSession;

  /** Conversation log ID (UUID) generated by geminiChatService for this turn — use to correlate server_runtime_logs */
  conversationLogId?: string;

  /** Token usage for this turn */
  tokenUsage?: TurnTokenUsage;


  // ---- Error ----
  /** Error message (if failed) */
  error?: string;

  // ---- Raw Response (for action routing) ----
  /** Raw AI response for App.tsx to route to action handlers */
  rawResponse?: AIActionResponse;

  // ---- Action-Specific Results (Phase 4) ----

  /** Selfie image result (if selfie action succeeded) */
  selfieImage?: {
    base64: string;
    mimeType: string;
  };
  selfieHistoryId?: string | null;
  selfieScene?: string | null;
  selfieMood?: string | null;

  /** Selfie error message (if selfie action failed) */
  selfieError?: string;

  /** Selfie message text for TTS (Phase 5) */
  selfieMessageText?: string;

  /** Video URL result (if video action succeeded) */
  videoUrl?: string;
  videoScene?: string | null;
  videoMood?: string | null;

  /** Video error message (if video action failed) */
  videoError?: string;

  /** Video message text for TTS */
  videoMessageText?: string;

  /** Detected email action for App.tsx to execute (archive / reply / dismiss) */
  detectedEmailAction?: {
    action: 'archive' | 'reply' | 'dismiss';
    message_id: string;
    thread_id?: string;
    reply_body?: string;
  };

  /** Pending tweet draft for UI approval card */
  pendingTweetDraft?: PendingTweetDraft;

  /** GIF search query or tag for GIPHY (server selects MP4 rendition) */
  gifQuery?: string;
  gifMessageText?: string;
  stickerBuffer?: Uint8Array;
  rawGeneratedStickerBase64?: string;

}

// ============================================================================
// ACTION HANDLER INTERFACES
// ============================================================================

/**
 * Standardized result from any action handler
 */
export interface ActionHandlerResult {
  /** Whether this handler processed the action */
  handled: boolean;

  /** Whether processing succeeded (only relevant if handled=true) */
  success: boolean;

  /** Messages to add to chat */
  chatMessages: ChatMessage[];

  /** Audio to play */
  audioToPlay?: string;

  /** Should refresh calendar */
  refreshCalendar?: boolean;

  /** Error message (if failed) */
  error?: string;
}

/**
 * Context passed to action handlers
 */
export interface ActionContext {
  /** Original user message */
  userMessage: string;

  /** Current chat history */
  chatHistory: ChatMessage[];

  /** Whether audio is muted */
  isMuted: boolean;
}

// ============================================================================
// HELPER TYPE GUARDS
// ============================================================================

/**
 * Check if a value is a valid ActionType
 */
export function isValidActionType(value: string): value is ActionType {
  return Object.values(ActionType).includes(value as ActionType);
}

/**
 * Check if a value is a valid CalendarQueryType
 */
export function isValidCalendarQueryType(value: string): value is CalendarQueryType {
  return Object.values(CalendarQueryType).includes(value as CalendarQueryType);
}

/**
 * Check if a value is a valid ProcessingStage
 */
export function isValidProcessingStage(value: string): value is ProcessingStage {
  return Object.values(ProcessingStage).includes(value as ProcessingStage);
}

// ============================================================================
// FACTORY FUNCTIONS
// ============================================================================

/**
 * Create a default (empty) orchestrator result
 */
export function createEmptyResult(stage: ProcessingStage = ProcessingStage.PREPROCESSING): OrchestratorResult {
  return {
    success: false,
    actionType: ActionType.NONE,
    stage,
    chatMessages: [],
    refreshCalendar: false,
  };
}

/**
 * Create a success result with a single chat message
 */
export function createSuccessResult(
  textResponse: string,
  actionType: ActionType = ActionType.NONE
): OrchestratorResult {
  return {
    success: true,
    actionType,
    stage: ProcessingStage.COMPLETE,
    chatMessages: [{ role: 'model', text: textResponse }],
    refreshCalendar: false,
  };
}

/**
 * Create an error result
 */
export function createErrorResult(error: string, stage: ProcessingStage = ProcessingStage.ERROR): OrchestratorResult {
  return {
    success: false,
    actionType: ActionType.NONE,
    stage,
    chatMessages: [],
    refreshCalendar: false,
    error,
  };
}

/**
 * Create a default action handler result (not handled)
 */
export function createUnhandledResult(): ActionHandlerResult {
  return {
    handled: false,
    success: false,
    chatMessages: [],
  };
}

/**
 * Determine action type from AI response
 */
export function determineActionType(response: AIActionResponse): ActionType {
  if (response.selfie_action) return ActionType.SELFIE;
  if (response.video_action) return ActionType.VIDEO;
  if (response.gif_action) return ActionType.GIF;
  return ActionType.NONE;
}
